Telescope:
  - device_name: telescope_SAINTEX
    ip: 10.211.55.3:11111
    device_number: 0
    alt_limit: 20
    guider:
      PIX2TIME: 
        '+x': 61.77
        '-x': 61.78
        '+y': 61.87
        '-y': 61.78
      RA_AXIS: 'x'
      DIRECTIONS:
        '+x': East
        '-x': West
        '+y': South
        '-y': North
      PID_COEFFS:
        'x': {'p': 0.70, 'i': 0.02, 'd': 0.0}
        'y': {'p': 0.50, 'i': 0.02, 'd': 0.0}
        'set_x': 0.0
        'set_y': 0.0
      WAIT_TIME: 10
Focuser:
  - device_name: focuser_SAINTEX
    ip: 10.211.55.3:11111
    ip_old: localhost:8001
    device_number: 0
    focus_pos: 10000
Dome:
  - device_name: dome_SAINTEX
    ip: 10.211.55.3:11111
    device_number: 0
    focus_pos: 10000
Camera:
  - device_name: camera_SAINTEX
    ip: 10.211.55.3:11111
    device_number: 0
    temperature: -40
    flats:
      target_adu: [45000, 3000]
      bias_offset: 1000
      lower_exptime_limit: 0.1
      upper_exptime_limit: 10
    paired_devices: 
      Telescope: telescope_SAINTEX
      Focuser: focuser_SAINTEX
      FilterWheel: fw_SAINTEX
      ObservingConditions: weather_SAINTEX
      SafetyMonitor: safety_SAINTEX
      Dome: dome_SAINTEX
FilterWheel:
  - device_name: fw_SAINTEX
    ip: 10.211.55.3:11111 
    device_number: 0
ObservingConditions:
  - device_name: weather_SAINTEX
    ip: 10.211.55.3:11111
    device_number: 0
SafetyMonitor:
  - device_name: safety_SAINTEX
    ip: 10.211.55.3:11111
    device_number: 0