Telescope:
  - device_name: telescope_Callisto
    ip: localhost:11111
    device_number: 0
    pointing_threshold: 0.06 # arcmins
    guider:
      PIX2TIME:
        '+x': 69.32860207831231
        '-x': 69.05795081331794
        '+y': 69.32860207831231
        '-y': 69.32860207831231
      RA_AXIS: 'y'
      DIRECTIONS:
        '+x': North
        '-x': South
        '+y': East
        '-y': West
      PID_COEFFS:
        'x': {'p': 0.70, 'i': 0.02, 'd': 0.0}
        'y': {'p': 0.50, 'i': 0.02, 'd': 0.0}
        'set_x': 0.0
        'set_y': 0.0
      WAIT_TIME: 10
Focuser:
  - device_name: focuser_Callisto
    ip: localhost:11111
    device_number: 0
    focus_pos: 6955
Camera:
  - device_name: camera_Callisto
    ip: localhost:11111
    device_number: 0
    temperature: -60
    temperature_tolerance: 1
    flats:
      target_adu: [31500, 10500]
      bias_offset: 300
      lower_exptime_limit: 6
      upper_exptime_limit: 60
    paired_devices: 
      Telescope: telescope_Callisto
      Focuser: focuser_Callisto
      Dome: dome_Callisto
      FilterWheel: fw_Callisto
      ObservingConditions: weather_Callisto
      SafetyMonitor: safety_Callisto
Dome:
  - device_name: dome_Callisto
    ip: localhost:11111
    device_number: 0
FilterWheel:
  - device_name: fw_Callisto
    ip: localhost:11111 
    device_number: 0
ObservingConditions:
  - device_name: weather_Callisto
    ip: localhost:11111
    device_number: 0
SafetyMonitor:
  - device_name: safety_Callisto
    ip: localhost:11111
    device_number: 0
    time_to_safe: 30
Misc:
  # Webcam: http://172.16.0.198:8888/inside
  backup_time: '12:00'