Telescope:
  - device_name: telescope_observatoryname
    ip: localhost:11111
    device_number: 0
    pointing_threshold: 0.1 # arcmins
    settle_factor: 0.0 # exposure multiplier for calculated settle time after pointing (for SPIRIT like cameras)
    meridian_flip: false # enable automated meridian flips
    meridian_flip_min: 5 # minutes past meridian to trigger flip
    guider: # populated using calibrate_guiding sequence
      PIX2TIME: # ms/pixel for camera used for guiding
        +x: 71.62908053771561
        -x: 71.62926906533114
        +y: 71.62775367838461
        -y: 71.62771750106279
      RA_AXIS: "x"
      DIRECTIONS:
        +x: East
        -x: West
        +y: North
        -y: South
      PID_COEFFS: # defaults
        "x": { "p": 0.70, "i": 0.02, "d": 0.0 }
        "y": { "p": 0.50, "i": 0.02, "d": 0.0 }
        "set_x": 0.0
        "set_y": 0.0
      MIN_GUIDE_INTERVAL: 60 # seconds
Focuser:
  - device_name: focuser_observatoryname
    ip: localhost:11111
    device_number: 0
    focus_position: 10000
    settle_time: 3 # seconds
    connectable: true # optional, default: true
Camera:
  - device_name: camera_observatoryname
    ip: localhost:11111
    device_number: 0
    temperature: -20 # degrees Celsius
    temperature_tolerance: 1 # degrees Celsius
    cooling_timeout: 30 # minutes
    flats:
      target_adu: 31500 # ADU
      target_adu_tolerance: 10500 # ADU
      bias_offset: 300 # ADU
      lower_exptime_limit: 1 # seconds
      upper_exptime_limit: 60 # seconds
    paired_devices:
      Telescope: telescope_observatoryname
      Focuser: focuser_observatoryname
      Dome: dome_observatoryname
      FilterWheel: fw_observatoryname
      ObservingConditions: weather_observatoryname
      SafetyMonitor: safety_observatoryname
      Camera: camera_observatoryname
Dome:
  - device_name: dome_observatoryname
    ip: localhost:11111
    device_number: 0
    close_dome_on_telescope_error: false
    telescopes:
      - telescope_observatoryname
FilterWheel:
  - device_name: fw_observatoryname
    ip: localhost:11111
    device_number: 0
ObservingConditions:
  - device_name: weather_observatoryname
    ip: localhost:11111
    device_number: 0
    polling_interval: 5 # seconds
    closing_limits:
      Humidity:
        - upper: 70
          max_safe_duration: 30
        - upper: 80
          max_safe_duration: 150
        - upper: 90
          max_safe_duration: 300
      Temperature:
        - lower: 0
          max_safe_duration: 30
      WindSpeed:
        - upper: 10
          max_safe_duration: 30
      SkyTemperature:
        - upper: -30
          max_safe_duration: 30
      RelativeSkyTemp:
        - upper: -40
          max_safe_duration: 30
SafetyMonitor:
  - device_name: safety_observatoryname
    ip: localhost:11111
    device_number: 0
    max_safe_duration: 15 # minutes

Misc:
  backup_time: "12:00" # UTC back up time of polled data (e.g. CCDTemperature) and logs


  # Webcam: http://localhost:8888/inside
  ## Multiple webcams:
  # Webcam:
  #   - name: Inside View
  #     url: http://localhost:8888/inside
  #   - name: Outside View
  #     url: http://localhost:8888/outside

  # AllSky: /path/to/allsky.jpg
  ## Multiple all-sky cameras:
  # AllSky:
  #   - name: East Sky
  #     path: /path/to/allsky_east.jpg
  #   - name: West Sky
  #     path: /path/to/allsky_west.jpg

  # filename_templates:
  #   object: "{action_date}/{device}_{filter_name}_{object_name}_{exptime:.3f}_{timestamp}.fits"
  #   calibration: "{action_date}/{device}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
  #   flats: "{action_date}/{device}_{filter_name}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
  #   autofocus: "autofocus/{action_date}/{device}_{filter_name}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
  #   calibrate_guiding: "calibrate_guiding/{action_date}/{device}_{filter_name}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
  #   pointing_model: "pointing_model/{action_date}/{device}_{filter_name}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
  #   default: "{action_date}/{device}_{filter_name}_{imagetype}_{exptime:.3f}_{timestamp}.fits"
